sonar.projectKey=Phoenix-Event-Ticketing_phoenix-online-ticket-inventory-service
sonar.organization=phoenix-event-ticketing
sonar.projectName=phoenix-online-ticket-inventory-service
sonar.sources=.
sonar.tests=.
sonar.test.inclusions=**/*_test.go
sonar.exclusions=**/vendor/**,**/go-cover.txt
sonar.go.coverage.reportPaths=go-cover.txt