sonar.organization=phoenix-event-ticketing
sonar.projectKey=Phoenix-Event-Ticketing_phoenix-online-ticket-inventory-service
sonar.projectName=phoenix-online-ticket-inventory-service
sonar.sources=.
sonar.tests=.
sonar.test.inclusions=**/*_test.go
sonar.exclusions=**/vendor/**,**/coverage.out
sonar.go.coverage.reportPaths=coverage.out